"""

Revision ID: 8ca60d161057
Revises: 7cba2ea5fc18
Create Date: 2023-02-03 11:53:18.484121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ca60d161057"
down_revision = "7cba2ea5fc18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
