"""

Revision ID: 917f601863e6
Revises: 8ca60d161057
Create Date: 2023-02-03 11:54:07.421429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "917f601863e6"
down_revision = "8ca60d161057"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
